apiVersion: v1
kind: Service
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  externalIPs:
  - 10.38.11.11
  ports:
  - port: 9091
    protocol: TCP
  selector:
    app: transmission
